mypro/accounts/urls.py
from django.urls import path, include
from .views import LoginView, profile, LogoutView, SignupView, ProfileUpdateView
from . import api

app_name = "accounts"

urlpatterns_api_v1 = [
    path("status/", api.status, name="status"),
]

urlpatterns = [
    path("api/", include((urlpatterns_api_v1, "api-v1"))),
    path("signup/", SignupView.as_view(), name="signup"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", profile, name="profile"),
    path("profile/edit/", ProfileUpdateView.as_view(), name="profile_edit"),
]

mypro/blog/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter
from . import views
from . import api
from .api import PostModelViewSet, TodoViewSet

router = DefaultRouter()
router.register(prefix="posts", viewset=PostModelViewSet)
router.register(prefix="todos", viewset=TodoViewSet)

urlpatterns = [
    # path("", TemplateView.as_view(template_name="blog/index.html"), name="index"),
    path("", views.index, name="index"),
    path("whoami/", views.whoami, name="whoami"),
]
urlpatterns_api_v1 = []
urlpatterns_api_v1 += router.urls

# urlpatterns_api_v1 = [
#     path("", api.post_list, name="post_list"),
#     path("<int:pk>/", api.post_detail, name="post_detail"),
#     path("new/", api.post_list, name="post_new"),
#     path("<int:pk>/edit/", api.post_detail, name="post_edit"),
#     path("<int:pk>/delete/", api.post_detail, name="post_delete"),
# ]

urlpatterns += [
    path("api/", include((urlpatterns_api_v1, "api-v1"))),
]

mypro/config/urls.py
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django_nextjs.render import render_nextjs_page


async def root(request):
    return await render_nextjs_page(request)

urlpatterns = [
    path("", root),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("blog/", include("blog.urls")),
    path("", include("photolog.urls")),
    path("", include("core.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if apps.is_installed("debug_toolbar"):
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

mypro/core/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = "core"

urlpatterns = [
    # path("", TemplateView.as_view(template_name="root.html"), name="root"),
    ]

mypro/photolog/urls.py
from django.urls import path
from .views import index, note_edit, NoteCreateView, NoteDetailView, CommentCreateView, CommentListView, CommentUpdateView, CommentDeleteView, user_page, user_follow, following_user_list, discover_user_list

app_name = "photolog"

urlpatterns = [
    path("", index, name="index"),
    path("users/following/", following_user_list, name="following_user_list"),
    path("users/discover/", discover_user_list, name="discover_user_list"),
    path("new/", NoteCreateView.as_view(), name="note_new"),
    path("@<username>/", user_page, name="user_page"),
    path(
        "@<username>/follow/",
        user_follow,
        name="user_follow",
        kwargs={"action": "follow"},
    ),
    path(
        "@<username>/unfollow/",
        user_follow,
        name="user_unfollow",
        kwargs={"action": "unfollow"},
    ),
    path("<int:pk>/", NoteDetailView.as_view(), name="note_detail"),
    path("<int:pk>/edit/", note_edit, name="note_edit"),
    path("<int:note_pk>/comments/", CommentListView.as_view(), name="comment_list"),
    path("<int:note_pk>/comments/new/", CommentCreateView.as_view(), name="comment_new"),
    path(
        "<int:note_pk>/comments/<int:pk>/edit/", CommentUpdateView.as_view(), name="comment_edit"
    ),
        path(
        "<int:note_pk>/comments/<int:pk>/delete/",
        CommentDeleteView.as_view(),
        name="comment_delete",
    ),
]

mypro/core/models.py
# Create your models here.

mypro/core/views.py
# Create your views here.

mypro/core/templates/_crispy_form.html
{% load crispy_forms_tags %}

<div class="row py-5">
    <div class="col-sm-8 offset-sm-2">
        <div class="card">
            {% if form_title %}
                <div class="card-header">
                    {{ form_title }}
                </div>
            {% endif %}
            <div class="card-body">
                {% if form.helper %}
                    {% crispy form form.helper %}
                {% else %}
                    {% crispy form %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

mypro/core/templates/_crispy_form_and_formset.html
{% load crispy_forms_tags %}

<form {% if form_action %}action="{{ form_action }}"{% endif %}
      method="post"
      {% if form.is_multipart or formset.is_multipart %}enctype="multipart/form-data"{% endif %}
      novalidate
>
    <div class="row py-5">
        <div class="col-sm-8 offset-sm-2">
            <div class="card">
                {% if form_title %}
                    <div class="card-header">
                        {{ form_title }}
                    </div>
                {% endif %}
                <div class="card-body">
                    {% if form %}
                        {% crispy form %}
                    {% endif %}
                    {% if formset %}
                        {% crispy formset %}
                    {% endif %}
                </div>
                <div class="card-footer">
                    <input type="submit" class="btn btn-primary w-100"
                           {% if form_submit_label %}value="{{ form_submit_label }}"{% endif %}
                    />
                </div>
            </div>
        </div>
    </div>
</form>

mypro/core/templates/_messages_as_event.html
{% if messages %}
    {% for message in messages %}
        <script>
          (function () {
            const tag = "{{ message.level_tag }}";
            const message = "{{ message }}"
            /* body 요소에 toast-message 이벤트를 보냅니다. */
            htmx.trigger(document.body, 'toast-message', {message: message, tag: tag});
          })();
        </script>
    {% endfor %}
{% endif %}

mypro/core/templates/base.html
{% load component_tags static %}

<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>장고 프로젝트</title>
    <link rel="stylesheet" href="{% static 'bootstrap/5.3.3/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'bootstrap-icons/1.11.3/font/bootstrap-icons.min.css' %}" />
    {% component_css_dependencies %}
</head>
<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}' data-bs-theme="dark">

<header class="p-3 text-bg-dark">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
            장고 프로젝트
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{% url 'photolog:index' %}" class="nav-link px-2 text-white">타임라인</a></li>
            <li><a href="{% url 'photolog:note_new' %}" class="nav-link px-2 text-white">새 기록</a></li>
            <li><a href="{% url 'photolog:following_user_list' %}" class="nav-link px-2 text-white">팔로잉</a></li>
            <li><a href="{% url 'photolog:discover_user_list' %}" class="nav-link px-2 text-white">찾기</a></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search"
        action="{% url 'photolog:index' %}"
        >
        <input type="search" name="query" value="{{ query }}" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
        </form>

        <div class="text-end">
            {% if not user.is_authenticated %}
            {% url 'accounts:login' as login_url %}
            <a href="{{ login_url }}{% if login_url != request.path %}?next={{ request.path }}{% endif %}"
               class="btn btn-outline-light me-2">로그인</a>
            <a href="{% url 'accounts:signup' %}?next={{ request.path }}"
               class="btn btn-warning">회원가입</a>
        {% else %}
            <a href="{% url 'accounts:profile' %}"
               class="btn btn-outline-light me-2">프로필</a>
            <a hx-post="{% url 'accounts:logout' %}?next={{ request.path }}"
               hx-target="body"
               hx-push-url="true"
               class="btn btn-warning">로그아웃</a>
            {% endif %}
        </div>
        </div>
    </div>
</header>

<main class="py-5">
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</main>

<footer class="text-body-secondary py-5">
    <div class="container">
        &copy; 파이썬 사랑방
    </div>
</footer>

{% if debug %}
    <script src="{% static 'htmx/1.9.12/htmx.js' %}"></script>
{% else %}
    <script src="{% static 'htmx/1.9.12/htmx.min.js' %}"></script>
{% endif %}
<script src="{% static 'bootstrap/5.3.3/js/bootstrap.min.js' %}"></script>
{% component_js_dependencies %}
<script src="{% static 'htmx/ext/hx-get-with-timestamp.js' %}"></script>
<script src="{% static 'observe-node-insertion.js' %}"></script>
<script src="{% static 'hashtag-linkify.js' %}"></script>
<script src="{% static "toast-messages.js" %}"></script>

{% include "_messages_as_event.html" %}

<script>
    document.body.addEventListener("htmx:responseError", event => {
      console.error("HTMX 요청 에러:", event.detail);
      const message = event.detail.error;
      const tag = "error";
      htmx.trigger(document.body, "toast-message", { message, tag });
    });
</script>

</body>
</html>

mypro/core/templates/crispy_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    {% include "_crispy_form.html" with form=form form_title=form_title %}
{% endblock %}

mypro/core/templates/crispy_form_and_formset.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    {% include "_crispy_form_and_formset.html" with form=form formset=formset form_title=form_title form_submit_label=form_submit_label %}
{% endblock %}

mypro/core/templates/nextjs_base.html
{# core/templates/nextjs_base.html #}

{% extends "django_nextjs/document_base.html" %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'bootstrap/5.3.3/css/bootstrap.min.css' %}"/>

    {# <head> 태그 시작 #}
    {{ block.super }}
    {# </head> 태그 끝 #}
{% endblock %}

{% block body %}
    <div class="container">
        <h1>장고 레이아웃 템플릿</h1>

        {# <body> 태그 시작 #}
        {{ block.super }}
        {# </body> 태그 끝 #}

        {% block django_content %}{% endblock %}
    </div>
{% endblock %}

mypro/core/templates/root.html
{% extends "base.html" %}
{% load component_tags %}

{% block content %}
    root.html

    {# {% component "modal-form" %}{% endcomponent %} #}
{% endblock %}