mypro/blog/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter
from . import views
from . import api
from .api import PostModelViewSet, TodoViewSet

router = DefaultRouter()
router.register(prefix="posts", viewset=PostModelViewSet)
router.register(prefix="todos", viewset=TodoViewSet)

urlpatterns = [
    # path("", TemplateView.as_view(template_name="blog/index.html"), name="index"),
    path("", views.index, name="index"),
    path("whoami/", views.whoami, name="whoami"),
]
urlpatterns_api_v1 = []
urlpatterns_api_v1 += router.urls

# urlpatterns_api_v1 = [
#     path("", api.post_list, name="post_list"),
#     path("<int:pk>/", api.post_detail, name="post_detail"),
#     path("new/", api.post_list, name="post_new"),
#     path("<int:pk>/edit/", api.post_detail, name="post_edit"),
#     path("<int:pk>/delete/", api.post_detail, name="post_delete"),
# ]

urlpatterns += [
    path("api/", include((urlpatterns_api_v1, "api-v1"))),
]

mypro/config/urls.py
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django_nextjs.render import render_nextjs_page


async def root(request):
    return await render_nextjs_page(request)

urlpatterns = [
    path("", root),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("blog/", include("blog.urls")),
    path("", include("photolog.urls")),
    path("", include("core.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if apps.is_installed("debug_toolbar"):
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

mypro/photolog/urls.py
from django.urls import path
from .views import index, note_edit, NoteCreateView, NoteDetailView, CommentCreateView, CommentListView, CommentUpdateView, CommentDeleteView, user_page, user_follow, following_user_list, discover_user_list

app_name = "photolog"

urlpatterns = [
    path("", index, name="index"),
    path("users/following/", following_user_list, name="following_user_list"),
    path("users/discover/", discover_user_list, name="discover_user_list"),
    path("new/", NoteCreateView.as_view(), name="note_new"),
    path("@<username>/", user_page, name="user_page"),
    path(
        "@<username>/follow/",
        user_follow,
        name="user_follow",
        kwargs={"action": "follow"},
    ),
    path(
        "@<username>/unfollow/",
        user_follow,
        name="user_unfollow",
        kwargs={"action": "unfollow"},
    ),
    path("<int:pk>/", NoteDetailView.as_view(), name="note_detail"),
    path("<int:pk>/edit/", note_edit, name="note_edit"),
    path("<int:note_pk>/comments/", CommentListView.as_view(), name="comment_list"),
    path("<int:note_pk>/comments/new/", CommentCreateView.as_view(), name="comment_new"),
    path(
        "<int:note_pk>/comments/<int:pk>/edit/", CommentUpdateView.as_view(), name="comment_edit"
    ),
        path(
        "<int:note_pk>/comments/<int:pk>/delete/",
        CommentDeleteView.as_view(),
        name="comment_delete",
    ),
]

mypro/photolog/models.py
import re

from io import BytesIO
from os.path import splitext
from typing import List
from uuid import uuid4

from PIL import Image
from django.core.files import File
from django.core.files.base import ContentFile
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.encoding import force_str
from django_lifecycle import LifecycleModelMixin, hook, BEFORE_SAVE, AFTER_SAVE
from taggit.managers import TaggableManager

from accounts.models import User


class Note(LifecycleModelMixin, models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tags = TaggableManager()

    class Meta:
        ordering = ["-pk"]

    def get_absolute_url(self) -> str:
        return reverse("photolog:note_detail", args=[self.pk])
    
    @hook(AFTER_SAVE, when="content", has_changed=True)
    def on_content_saved(self):
        hashtags: List[str] = re.findall(r"#(\w+)", self.content)
        self.tags.set(hashtags, clear=True)
    

def uuid_name_upload_to(instance: models.Model, filename: str) -> str:
    app_label = instance.__class__._meta.app_label
    cls_name = instance.__class__.__name__.lower()
    ymd_path = force_str(timezone.now().strftime("%Y/%m/%d"))
    extension = splitext(filename)[-1].lower()
    new_filename = uuid4().hex + extension
    return "/".join((app_label, cls_name, ymd_path, new_filename))


class Photo(LifecycleModelMixin, models.Model):
    note = models.ForeignKey(Note, on_delete=models.CASCADE)
    image = models.ImageField(
        # upload_to="photolog/photo/%Y/%m/%d",
        upload_to=uuid_name_upload_to,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @classmethod
    def make_thumb(
        cls, image_file: File, max_width: int = 1024, max_height: int = 1024, quality=80
    ) -> File:
        pil_image = Image.open(image_file)
        max_size = (max_width, max_height)
        pil_image.thumbnail(max_size)
        if pil_image.mode == "RGBA":
            pil_image = pil_image.convert("RGB")

        thumb_name = splitext(image_file.name)[0] + ".jpg"
        thumb_file = ContentFile(b"", name=thumb_name)
        pil_image.save(thumb_file, format="jpeg", quality=quality)

        return thumb_file

    @classmethod
    def create_photos(cls, note: Note, photo_file_list: List[File]) -> List["Photo"]:
        if not note.pk:
            raise ValueError("Note를 먼저 저장해주세요.")

        photo_list = []
        for photo_file in photo_file_list:
            photo = cls(note=note)
            photo.image.save(photo_file.name, photo_file, save=False)
            photo_list.append(photo)

        cls.objects.bulk_create(photo_list)

        return photo_list

    @hook(BEFORE_SAVE, when="image", has_changed=True)
    def on_image_changed(self):
        if self.image:
            image_width = self.image.width
            image_extension = splitext(self.image.name)[-1].lower()

            if image_width > 1024 or image_extension not in (".jpg", ".jpeg"):
                thumb_file = self.make_thumb(self.image.file, 1024, 1024, 80)
                self.image.save(thumb_file.name, thumb_file, save=False)


class Comment(models.Model):
    note = models.ForeignKey(Note, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-pk"]

mypro/photolog/views.py
from typing import Literal

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, ListView, DeleteView
from django_htmx.http import trigger_client_event, HttpResponseClientRedirect


from accounts.models import User
from core.decorators import login_required_hx
from photolog.forms import (
    NoteCreateForm,
    PhotoUpdateFormSet,
    NoteUpdateForm,
    CommentForm,
)
from photolog.models import Note, Photo, Comment


def index(request):
    if not request.user.is_authenticated:
        note_qs = Note.objects.all()
    else:
        user: User = request.user
        note_qs = Note.objects.filter(
            Q(author=user) | Q(author__in=user.following_user_set.all())
        )

    query = request.GET.get("query", "").strip()
    if query:
        note_qs = note_qs.filter(Q(title__icontains=query) | Q(author__username=query))

    tag_name = request.GET.get("tag", "").strip()
    if tag_name:
        note_qs = note_qs.filter(tags__name__in=[tag_name])

    note_qs = note_qs.select_related("author").prefetch_related("photo_set", "tags")
    
    return render(
        request,
        "photolog/index.html",
        {
            "note_list": note_qs,
            "query": query,
        },
    )


@login_required
def following_user_list(request):
    user: User = request.user
    user_qs = user.following_user_set.exclude(id__in=[user.pk]).select_related(
        "profile"
    )
    return render(
        request,
        "photolog/user_list.html",
        {
            "user_list": user_qs,
            "is_follower": True,
        },
    )


@login_required
def discover_user_list(request):
    user: User = request.user
    user_qs = (
        User.objects.exclude(id__in=[user.pk])
        .exclude(id__in=user.following_user_set.all())
        .select_related("profile")
    )
    return render(
        request,
        "photolog/user_list.html",
        {
            "user_list": user_qs,
            "is_follower": False,
        },
    )


def user_follow(request, username: str, action: Literal["follow", "unfollow"]):
    from_user: User = request.user
    to_user = get_object_or_404(User, is_active=True, username=username)

    if request.method == "GET":
        if from_user.is_authenticated:
            is_follower = from_user.is_follower(to_user)
        else:
            is_follower = False
    else:
        if from_user.is_authenticated:
            if action == "follow":
                from_user.follow(to_user)
                is_follower = True
            else:
                from_user.unfollow(to_user)
                is_follower = False
        else:
            next_url = request.META.get("HTTP_HX_CURRENT_URL", "")
            redirect_url = reverse("accounts:login") + "?next=" + next_url
            return HttpResponseClientRedirect(redirect_url)

    return render(
        request,
        "photolog/_user_follow.html",
        {
            "is_follower": is_follower,
            "username": username,
        },
    )


class NoteCreateView(LoginRequiredMixin, CreateView):
    model = Note
    form_class = NoteCreateForm
    template_name = "crispy_form.html"
    extra_context = {"form_title": "새 기록"}

    def form_valid(self, form):
        self.object = form.save(commit=False)  # noqa

        new_note = self.object
        new_note.author = self.request.user
        new_note.save()

        photo_file_list = form.cleaned_data.get("photos")
        if photo_file_list:
            Photo.create_photos(new_note, photo_file_list)

        messages.success(self.request, "새 기록을 저장했습니다.")

        return redirect(self.get_success_url())


@login_required
def note_edit(request, pk):
    note = get_object_or_404(Note, pk=pk, author=request.user)
    photo_qs = note.photo_set.all()

    if request.method == "GET":
        note_form = NoteUpdateForm(instance=note, prefix="note")
        photo_formset = PhotoUpdateFormSet(
            queryset=photo_qs,
            instance=note,
            prefix="photos",
        )
    else:
        note_form = NoteUpdateForm(
            data=request.POST, files=request.FILES, instance=note, prefix="note"
        )
        photo_formset = PhotoUpdateFormSet(
            queryset=photo_qs,
            instance=note,
            data=request.POST,
            files=request.FILES,
            prefix="photos",
        )

        if note_form.is_valid() and photo_formset.is_valid():
            saved_note = note_form.save()

            # 새롭게 생성되는 Photo
            photo_file_list = note_form.cleaned_data.get("photos")
            if photo_file_list:
                Photo.create_photos(saved_note, photo_file_list)

            # 기존 Photo 수정
            photo_formset.save()

            messages.success(request, f"기록#{saved_note.pk}을 수정했습니다.")

            return redirect(saved_note)
        
    return render(
        request,
        "crispy_form_and_formset.html",
        {
            "form_title": "기록 수정",
            "form": note_form,
            "formset": photo_formset,
            "form_submit_label": "저장하기",
        },
    )


class NoteDetailView(DetailView):
    model = Note

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        note = self.object
        context_data["comment_list"] = note.comment_set.select_related(
            "author__profile"
        )
        return context_data


class CommentListView(ListView):
    model = Comment
    template_name = "photolog/_comment_list.html"

    def get_queryset(self):
        note_pk = self.kwargs["note_pk"]
        qs = super().get_queryset()
        qs = qs.filter(note__pk=note_pk)
        qs = qs.select_related("author__profile")

        return qs


def user_page(request, username):
    author = get_object_or_404(User, is_active=True, username=username)

    note_qs = Note.objects.filter(author=author)
    note_qs = note_qs.select_related("author").prefetch_related("photo_set", "tags")

    return render(
        request,
        "photolog/user_page.html",
        {
            "author": author,
            "note_list": note_qs,
        },
    )


@method_decorator(login_required_hx, name="dispatch")
class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = "photolog/_comment_form.html"

    def dispatch(self, request, *args, **kwargs):
        note_pk = self.kwargs["note_pk"]
        self.note = get_object_or_404(Note, pk=note_pk)  # noqa
        return super().dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs

    def form_valid(self, form):  # 유효성 검사가 끝나고 나서 호출
        comment = form.save(commit=False)
        comment.author = self.request.user
        comment.note = self.note
        comment.save()

        messages.success(self.request, "태그를 저장했습니다.")

        response = render(self.request, "_messages_as_event.html")
        response = trigger_client_event(response, "refresh-comment-list")

        return response
    

@method_decorator(login_required_hx, name="dispatch")
class CommentUpdateView(UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = "photolog/_comment_form.html"

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(author=self.request.user)
        return qs

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs

    def form_valid(self, form):  # 유효성 검사가 끝나고 나서 호출
        form.save()

        messages.success(self.request, "태그를 저장했습니다.")

        response = render(self.request, "_messages_as_event.html")
        response = trigger_client_event(response, "refresh-comment-list")

        return response


@method_decorator(login_required_hx, name="dispatch")
class CommentDeleteView(DeleteView):
    model = Comment

    def get_queryset(self):
        note_pk = self.kwargs["note_pk"]
        qs = super().get_queryset()
        qs = qs.filter(note__pk=note_pk, author=self.request.user)
        return qs

    def form_valid(self, form):
        self.object.delete()

        messages.success(self.request, "댓글을 삭제했습니다.")

        response = render(self.request, "_messages_as_event.html")
        response = trigger_client_event(response, "refresh-comment-list")

        return response

mypro/photolog/templates/photolog/_comment_form.html
{% load component_tags crispy_forms_tags partials %}

{% partialdef form %}
    {% crispy form %}
{% endpartialdef %}

{% if request.method == "POST" %}
    {% partial form %}
{% else %}
    {% component "modal-form" %}
        {% fill "modal-title" %}
            {% if not form.instance.pk %}새 댓글{% else %}댓글 수정{% endif %}
        {% endfill %}
        {% fill "modal-body" %}
            {% partial form %}
        {% endfill %}
    {% endcomponent %}
    <script>
      (function() {
        const modalEl = document.currentScript.previousElementSibling;
        document.body.addEventListener("refresh-comment-list", () => {
          htmx.trigger(modalEl, "hide");
        });
      })();
    </script>
{% endif %}

mypro/photolog/templates/photolog/_comment_list.html
{% load i18n %}

{% for comment in comment_list %}
    <div class="d-flex flex-row p-3">
        {% if comment.author.profile.avatar %}
            <img src="{{ comment.author.profile.avatar.url }}"
                 class="rounded-circle me-3"
                 style="width: 60px; height: 60px;"
                 alt="{{ comment.author.username }}'s Avatar">
        {% endif %}
        <div class="w-100">
            <div class="d-flex flex-row align-items-center gap-3">
                <a href="{% url 'photolog:user_page' comment.author.username %}"
                   class="text-white text-decoration-none"
                >{{ comment.author.username }}</a>
                {% language "en-us" %}
                    {{ comment.created_at|timesince }} ago
                {% endlanguage %}
            </div>
            <div class="mb-1">
                {{ comment.message }}
            </div>
            <div class="d-flex flex-row gap-2">
                {% if comment.author == user %}
                    <a href="#"
                       hx-get="{% url 'photolog:comment_edit' comment.note.pk comment.pk %}"
                       hx-get-with-timestamp
                       hx-target="body"
                       hx-swap="beforeend"  {# body 내용 끝에 추가 #}
                       class="text-white text-decoration-none">
                        수정하기
                    </a>
                    <a href="#"
                       hx-post="{% url 'photolog:comment_delete' comment.note.pk comment.pk %}"
                       hx-confirm="Are you sure?"
                       hx-swap="none"
                       class="text-white text-decoration-none"
                    >
                        삭제하기
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
{% endfor %}

mypro/photolog/templates/photolog/_note_list.html
{% load component_tags %}

<div class="container">
    <div class="row">
        {% for note in note_list %}
            {% component "image-overlay" class="col-xl-3 col-lg-4 col-md-6 mt-4" %}
                {% fill "href" %}{% url 'photolog:note_detail' note.pk %}{% endfill %}
                {% fill "img-src" %}{{ note.photo_set.all.0.image.url }}{% endfill %}
                {% fill "text" %}
                    {{ note.title }}<br/>
                    <small>by {{ note.author.username }}</small>
                    <small class="d-block mt-3 text-muted">
                        {% for tag in note.tags.all %}
                            {% if forloop.counter0 < 5 %}
                                #{{ tag.name }}
                            {% endif %}
                        {% endfor %}
                    </small>
                {% endfill %}
            {% endcomponent %}
        {% endfor %}
    </div>
</div>

mypro/photolog/templates/photolog/_user_follow.html
{% if request.user.username != username %}
    {% if is_follower %}
        <a href="#"
           hx-post="{% url 'photolog:user_unfollow' username %}"
           hx-swap="outerHTML"
           class="btn btn-sm btn-primary">
            <i class="bi bi-person-check-fill"></i>
            팔로잉 중
        </a>
    {% else %}
        <a href="#"
           hx-post="{% url 'photolog:user_follow' username %}"
           hx-swap="outerHTML"
           class="btn btn-sm btn-secondary">
            <i class="bi bi-person-add"></i>
            팔로잉 하기
        </a>
    {% endif %}
{% endif %}

mypro/photolog/templates/photolog/base.html
{% extends "base.html" %}

{% block content %}
    {% block photolog-content %}
    {% endblock %}
{% endblock %}

mypro/photolog/templates/photolog/index.html
{% extends "photolog/base.html" %}
{% load component_tags %}

{% block photolog-content %}
    {% include "photolog/_note_list.html" with note_list=note_list %}
{% endblock %}

mypro/photolog/templates/photolog/note_detail.html
{% extends "photolog/base.html" %}
{% load component_tags i18n %}

{% block photolog-content %}
    <div class="card">
        <div class="card-header">
            <div class="d-flex flex-row gap-2">
                {% if note.author.profile.avatar %}
                    <img src="{{ note.author.profile.avatar.url }}"
                         class="rounded-circle"
                         style="width: 40px; height: 40px;"
                         alt="" />
                {% endif %}
                <div class="w-100">
                    <div class="d-flex flex-column">
                        <a href="{% url 'photolog:user_page' note.author.username %}"
                           class="text-white text-decoration-none"
                        >
                            {{ note.author.username }}
                        </a>
                        {% language "en-us" %}
                            <span>{{ note.created_at|timesince }} ago</span>
                        {% endlanguage %}
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <h4>{{ note.title }}</h4>
                    <div data-hashtag-linkify="{% url 'photolog:index' %}?tag=">
                        {{ note.content|linebreaks }}
                    </div>
                </div>
                <div class="col-md-6">
                    {% component "carousel" photo_list=note.photo_set.all attr_name="image.url" %}{% endcomponent %}
                </div>
            </div>
        </div>
    </div>

    <div class="my-3">
        <a href="{% url 'photolog:index' %}" class="btn btn-primary">타임라인</a>
        {% if request.user == note.author %}
            <a href="{% url 'photolog:note_edit' note.pk %}" class="btn btn-success">수정하기</a>
        {% endif %}
    </div>

    <hr />

    <a href="{% url 'photolog:comment_new' note.pk %}"
       hx-get="{% url 'photolog:comment_new' note.pk %}"
       hx-with-timestamp
       hx-target="body"
       hx-swap="beforeend"  {# body 끝에 추가 #}
       class="btn btn-primary w-100"
    >댓글 쓰기</a>
    
    <div id="comment-list" class="my-3">
        {% include "photolog/_comment_list.html" with user=request.user comment_list=comment_list only %}
    </div>

    <a href="#"
       hx-get="{% url 'photolog:comment_list' note.pk %}"
       hx-get-with-timestamp
       hx-trigger="click, refresh-comment-list from:body"
       hx-target="#comment-list"
       class="btn btn-primary w-100">댓글 새로고침</a>

{% endblock %}

mypro/photolog/templates/photolog/user_list.html
{% extends "photolog/base.html" %}

{% block photolog-content %}
    <div class="row">
        {% for user in user_list %}
            <div class="col-xl-3 col-lg-4 col-md-6 mt-4">
                <div class="card h-100">
                    <div class="card-header">
                        <div class="d-flex flex-row align-items-center gap-2">
                            {% if user.profile.avatar %}
                                <img src="{{ user.profile.avatar.url }}"
                                     class="rounded-circle"
                                     style="width: 32px; height: 32px;"
                                     alt="">
                            {% else %}
                                <i class="bi bi-person-circle"
                                   style="font-size: 1.6rem;"
                                ></i>
                            {% endif %}
                            <a href="{% url 'photolog:user_page' user.username %}"
                               class="text-white text-decoration-none"
                            >
                                @{{ user.username }}
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <span class="text-muted">자기 소개가 없어요.</span>
                    </div>
                    <div class="card-footer">
                        {% include "photolog/_user_follow.html" with is_follower=is_follower username=user.username %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

mypro/photolog/templates/photolog/user_page.html
{% extends "photolog/base.html" %}
{% load component_tags %}

{% block photolog-content %}
    <div class="d-flex flex-column align-items-center gap-2 py-5 text-center">
        {% if author.profile.avatar %}
            <img src="{{ author.profile.avatar.url }}"
                 class="rounded-circle"
                 style="width: 128px;"
                 alt="{{ author.username }}'s Avatar" />
        {% endif %}

        <h2>@{{ author.username }}</h2>

        <div hx-get="{% url 'photolog:user_follow' author.username %}"
             hx-trigger="load"></div>
    </div>

    {% include "photolog/_note_list.html" with note_list=note_list %}
{% endblock %}